---
title: "Data tidy"
output: github_document
---

```{r setup}
library(tidyverse)

```

##'pivot)longer
load the pulse data
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()

```

Wide format to long format...

```{r}
pulse_data_tidy = 
  pulse_data%>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",#combine several bdi lines
    names_prefix = "bdi_score_",#delete prefix
    values_to = "bdi"#give a column name to the value of several bdi columns.
)%>%
  relocate(id,visit)%>%
  mutate(
    visit = replace(visit, visit =="bl","00m"),#replace bl with 00m
    visit = factor(visit)
  )
  

```

##pivot_wider
makeup a results data table
```{r}
analysis_df =
  tibble(
    group = c("treatment","treatment","control","control"),
    time = c("pre","post","pre","post"),
    group_mean = c(4, 8, 3, 6)
  )

analysis_df1 = analysis_df %>%
   pivot_wider(
     names_from = "time",
     values_from = "group_mean"
   )
# knitr::kable()#create a formal table of Makrdown
 


```
(what abou 'bind.rows()')
##bind_rows
import LotR
```{r}

library(readxl)

fellowship_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6")%>%
  mutate(movie = "fellowship_rings")

two_towers_df = 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6")%>%
  mutate(movie = "two_towers")

return_df = read_excel("data/LotR_Words.xlsx", range = "J3:L6")%>%
  mutate(movie = "return_king")#没跟上

lotr_df =
  bind_rows(fellowship_df, two_towers_df, return_df)%>%
  janitor::clean_names()%>%
  relocate(movie)%>%
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  )





```

##joining dataset
Import and clean the FAS datasets.
```{r}
pups_df =
  read_csv("./data/FAS_pups.csv")%>%
  janitor::clean_names()%>%
  mutate(sex = recode(sex,'1' = "male", '2' = "female"))

litters_df =
  read_csv("./data/FAS_litters.csv")%>%
  janitor::clean_names()%>%
  relocate(litter_number)%>%
  separate(group, into =c("dose", "day_of_tx"), sep = 3)



```

```{r}
fas_df =
  left_join(pups_df, litters_df, by = "litter_number")%>%
  arrange(litter_number)%>%
  relocate(litter_number, dose, day_of_tx)



```


```{r}



litters_df=
  read_csv("data/FAS_litters.csv")%>%
janitor::clean_names()

pups_df =
  read_csv("data/FAS_pups.csv")%>%
  janitor::clean_names()



```


```{r}



```





