---
title: "Data import"
output: github_document
---

```{r setup}
library(tidyverse)

```

```{r}
litter_df = read_csv("./data/FAS_litters.csv")
litter_df = janitor::clean_names(litter_df)
```

##'select' 

Choose some columns and not others

```{r}
x = select(litter_df, group, litter_number)
y = select(litter_df, group, gd0_weight : gd_of_birth)
```

```{r}
select(litter_df, -litter_number)

```


```{r}
##change name
x =select(litter_df, GROUP = group, LITTer_NUmBer = litter_number)
x
```


```{r}
rename(litter_df, GROUP = group, LITTer_NUmBer = litter_number)

```



```{r}
select(litter_df, starts_with("gd"))
##start with only gd
select(litter_df, litter_number, everything())
##start with litters_df, keeep everything

x= relocate(litter_df, litter_number)
#start with litters_df, keeep everything


```

##filter
```{r}
x = filter(litter_df, gd0_weight < 22)


y = filter(litter_df, gd_of_birth == 20)


z = filter(litter_df, gd_of_birth != 20)


ww=filter(litter_df, gd0_weight >=22, gd_of_birth == 20)


qw = filter(litter_df, group == "Mod8")

qw = filter(litter_df, group %in%c("Con7", "Mod8"))




```


## 'mutate'


```{r}
x = mutate(
  litter_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))



```

##arrange

```{r}
x = arrange(litter_df, pups_born_alive)
#sort by variable.
```

